#ifndef  _affichage_h_
#define _affichage_h_

//$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ Declarations des fonctions dans le .cpp $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
void affichageHeureNextion();
void affichePageBrassage();
void affichePageConfig();
void affichePageHorloge();
void affichePageInfo();
void affichePageMenu();
void affichePageTel();
void affichePageWifi();
void affichePageGraph7J();
void affichePageEtalonnage();
void affichePageSd();
void boutonBlanc(void *ptr);
void boutonBleu(void *ptr);
void boutonBrassage1(void *ptr);
void boutonBrassage2(void *ptr);
void boutonBrassage3(void *ptr);
void boutonNourrissageManuel(void *ptr);
void boutonOnOffAlim1(void *ptr);
void boutonOnOffAlim2(void *ptr);
void boutonOnOffRemonte(void *ptr);
void boutonminBrassage1(void *ptr);
void boutonminBrassage2(void *ptr);
void boutonminBrassage3(void *ptr);
void boutonoscillo1();
void boutonoscillo1max(void *ptr);
void boutonoscillo1min(void *ptr);
void boutonoscillo2();
void boutonoscillo2max(void *ptr);
void boutonoscillo2min(void *ptr);
void boutonoscillo3();
void boutonoscillo3max(void *ptr);
void boutonoscillo3min(void *ptr);
void boutonTempeteAleatoire(void *ptr);
void boutonTempeteManuel(void *ptr);
void versBasSd(void *ptr);
void versHautSd(void *ptr);
void effaceSd(void *ptr);
void redemarrage (void *ptr);
void effaceBufferTexte();
void effaceminuteEnTexteIn();
void avancementBarBrassage(uint8_t etape);
void enregistrerBrassage(void *ptr);
void avancementBarconfig(uint8_t etape);
void enregistrerConfig(void *ptr);
void enregistrerHorloge(void *ptr);
void enregistrerTel(void *ptr);
void enregistrerWifi(void *ptr);
void horraireEnSeconde(uint32_t h, uint16_t d, uint16_t m);
void afficherNourrissageEnCoursOff();
void numEnChar (uint8_t numeriqueEnChar);
void rafraichirBrassage1Nextion();
void rafraichirBrassage2Nextion();
void rafraichirBrassage3Nextion();
void rafraichirEclairageBlancNextion();
void rafraichirEclairageBleuNextion();
void rafraichirHeureSiSurMenu();
void rafraichirPhBacNextion();
void rafraichirRedoxNextion();
void rafraichirSaliniteNextion();
void rafraichirTemperatureBacNextion();
void rafraichirTemperatureRampeNextion();
void rafraichirIconeBatterie();
void rafraichirSignalWifi();
void rafraichirSignalGSM();
void rafraichirMesuresEtalonnage();
void reinitialisationDeLaffichage();
void statutBlanc();
void statutBleu();
void statutBrassage1();
void statutBrassage2();
void statutBrassage3();
void statutOnOffAlim1();
void statutOnOffAlim2();
void statutNourrissageEnCours();
void statutOnOffDelay();
void statutTempete();
void statutTempeteAleatoire();
void tempeteNextion();
void afficherNourrissageEnCours();
void versBrassage(void *ptr);
void versConfig(void *ptr);
void versHorloge(void *ptr);
void versInfo(void *ptr);
void versMenu(void *ptr);
void versTel(void *ptr);
void versWifi(void *ptr);
void versStandby(void *ptr);
void versChoixGraph(void *ptr);
void versGraph24H(void *ptr);
void versGraph7J(void *ptr);
void versEtalonnage(void *ptr);
void versSd(void *ptr);
void calibreSonde(void *ptr);
void sondeACalibrer(void *ptr);
void afficherAlerteOsmolation();
void afficherAlerteOsmolationOff();
void afficherAlerteOsmolationOffReserveVide();
void afficherAlertepPhBacBas();
void afficherAlertepPhBacHaut();
void afficherAlertepPhBacOff();
void afficherAlerteGodetPlein();
void afficherAlerteGodetOK();
void lectureBoutons();
void effaceLesEvenementsSurLecranSd();
void texteProgmemAuNextion(NexText, const char texteEnProgmem[] PROGMEM, const uint16_t couleurTexte);
void texteAuNextion(NexText champTexte, char*texte, const uint16_t couleurTexte);
void graphique24H(uint16_t T, uint16_t bufT, uint16_t Ph, uint16_t bufPh, uint16_t redox, uint16_t bufRedox,float Salinite, float bufSalinite);
void graphique7J(uint16_t T, uint16_t Ph, uint16_t redox, float Salinite);

#endif
